CREATE TABLE IF NOT EXISTS departments (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    prefix VARCHAR(10) NOT NULL,
    daily_quota INTEGER NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    break_start_time TIME,
    break_end_time TIME
);

CREATE TABLE IF NOT EXISTS counters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    department_code VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_counter_department FOREIGN KEY (department_code) REFERENCES departments(code)
);

CREATE TABLE IF NOT EXISTS ic_states (
    code VARCHAR(2) PRIMARY KEY,
    state_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS phone_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(100) NOT NULL,
    iso_code VARCHAR(2) NOT NULL UNIQUE,
    dial_code VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS queue_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_number VARCHAR(20) NOT NULL,
    identity_type VARCHAR(30) NOT NULL,
    identity_number VARCHAR(20) NOT NULL,
    phone_country_code VARCHAR(10) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    department_code VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    counter_name VARCHAR(80),
    queue_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    called_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT uq_queue_number_date UNIQUE (queue_number, queue_date),
    CONSTRAINT fk_ticket_department FOREIGN KEY (department_code) REFERENCES departments(code)
);

CREATE TABLE IF NOT EXISTS staff_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ticket_queue_date ON queue_tickets(queue_date);
CREATE INDEX IF NOT EXISTS idx_ticket_department_status ON queue_tickets(department_code, status, queue_date);
CREATE INDEX IF NOT EXISTS idx_ticket_identity ON queue_tickets(identity_type, identity_number, department_code, queue_date);
